# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
